#!/usr/bin/env php
<?php

/**
 * Run the automer test runner
 *
 * @author George Webb <george@webb.uno>
 */

// TODO: Check php version

require_once __DIR__ . '/vendor/autoload.php';

// TODO: Configure. CLI flags -> configuration file -> defaults/conventions

$container = new \Automer\Container();

$configuration = new \Automer\Configuration();
$container->configuration = $configuration;

$climate = new \League\CLImate\CLImate();
$container->climate = $climate;

$runner = new \Automer\Runner($container);
$runner->run();
