#!/usr/bin/env php
<?php

/**
 * Run the automer test runner
 *
 * @author George Webb <george@webb.uno>
 */

// TODO: Check php version

require_once __DIR__ . '/vendor/autoload.php';

// TODO: Configure. CLI flags -> configuration file -> defaults/conventions

$container = new \Automer\Container();

$container->configuration = new \Automer\Configuration();

$container->climate = new \League\CLImate\CLImate();

$container->output = new \Automer\Output($container, \Automer\Output::LEVEL_VVV); // TODO: Set level based on config

$error_handler = new \Automer\ErrorHandler($container);
$error_handler->register();

$runner = new \Automer\Runner($container);
$runner->run();
