#!/usr/bin/env php
<?php

/**
 * Run the automer test runner
 *
 * @author George Webb <george@webb.uno>
 */

// TODO: Check php version

require_once __DIR__ . '/vendor/autoload.php';

// TODO: Configure. CLI flags -> configuration file -> defaults/conventions

$configuration = new \Automer\Configuration();

$runner = new \Automer\Runner($configuration);
$runner->run();
